# Site settings
name: Eric Osowski
email: eric.j.osowski@icloud.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Python, Ruby, Machine Learning, Deep Learning, Startups, Agile, Pair Programming, Full Stack, CSS, HTML, Node, SQL, Sequelize, Mongo, Mongodb, Javascript"
skills: "Full Stack Developer serving the Minneapolis area"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/eric-osowski-155716137/
  - title: github
    url: https://github.com/EricJamesOsowski
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
